version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '0.0.0.0:8080:80'
    # entrypoint: 
      # - /entrypoint.sh
    # command: ["nginx", "-g", "daemon off;"]
    volumes:
      # - ./docker/entrypoint.sh:/entrypoint.sh
      - ./:/var/www/html/
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - vallheru

  php-fpm:
    image: library/php:5.6.27-fpm
    # command:
    #   - "-b"
    #   - "0.0.0.0:9000"
    entrypoint: 
      - /entrypoint.sh
    command: ["php-fpm"]
    volumes:
      - ./docker/entrypoint.sh:/entrypoint.sh
      - ./:/var/www/html
    networks:
      - vallheru

  mysql:
    image: mysql:5-debian
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./install/vallheru.sql:/docker-entrypoint-initdb.d/vallheru.sql
    environment:
      MYSQL_ROOT_PASSWORD: vallheru123
      MYSQL_DATABASE: vallheru
    networks:
      - vallheru

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    
    networks:
      - vallheru

volumes:
  mysql_data:
networks:
  vallheru: