version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '0.0.0.0:8080:80'
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - vallheru

  php-fpm:
    build:
      dockerfile: ./docker/php.Dockerfile
      context: .
    entrypoint: 
      - /entrypoint.sh
    command: ["php-fpm"]
    volumes:
      - ./docker/entrypoint.sh:/entrypoint.sh
      - ./:/var/www/html
    networks:
      - vallheru

  mysql:
    image: library/mysql:5.5
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: vallheru123
      MYSQL_DATABASE: vallheru
    networks:
      - vallheru

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    
    networks:
      - vallheru

volumes:
  mysql_data:
networks:
  vallheru: