ALTER TABLE `players` CHANGE `energy` `energy` DOUBLE( 11, 2 ) NOT NULL DEFAULT '10.00',
CHANGE `max_energy` `max_energy` DOUBLE( 11, 2 ) NOT NULL DEFAULT '100.00',
CHANGE `hp` `hp` INT( 11 ) UNSIGNED NOT NULL DEFAULT '10',
CHANGE `max_hp` `max_hp` INT( 11 ) NOT NULL DEFAULT '10',
CHANGE `antidote` `antidote` CHAR( 4 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
CHANGE `pm` `pm` INT( 11 ) NOT NULL DEFAULT '0';
ALTER TABLE `players`
  DROP `level`,
  DROP `exp`,
  DROP `strength`,
  DROP `agility`,
  DROP `inteli`,
  DROP `szyb`,
  DROP `wytrz`,
  DROP `wisdom`,
  DROP `ability`,
  DROP `atak`,
  DROP `unik`,
  DROP `magia`,
  DROP `alchemia`,
  DROP `shoot`,
  DROP `fletcher`,
  DROP `leadership`,
  DROP `breeding`,
  DROP `mining`,
  DROP `lumberjack`,
  DROP `herbalist`,
  DROP `jeweller`,
  DROP `thievery`,
  DROP `perception`,
  DROP `metallurgy`,
  DROP `crime`;
ALTER TABLE `players` ADD `stats` VARCHAR( 2048 ) NOT NULL DEFAULT 'strength:Siła,0,0,0;agility:Zręczność,0,0,0;condition:Kondycja,0,0,0;speed:Szybkość,0,0,0;inteli:Inteligencja,0,0,0;wisdom:Siła Woli,0,0,0;',
ADD `skills` VARCHAR( 4096 ) NOT NULL DEFAULT 'smith:Kowalstwo,1,0;shoot:Strzelectwo,1,0;alchemy:Alchemia,1,0;dodge:Uniki,1,0;carpentry:Stolarstwo,1,0;magic:Rzucanie Czarów,1,0;attack:Walka Bronią,1,0;leadership:Dowodzenie,1,0;breeding:Hodowla,1,0;mining:Górnictwo,1,0;lumberjack:Drwalnictwo,1,0;herbalism:Zielarstwo,1,0;jewellry:Jubilerstwo,1,0;smelting:Hutnictwo,1,0;thievery:Złodziejstwo,1,0;perception:Spostrzegawczość,1,0;',
ADD `bonuses` TEXT NOT NULL,
ADD `rinvite` INT( 11 ) NOT NULL DEFAULT '0',
ADD `tinvite` INT( 11 ) NOT NULL DEFAULT '0',
ADD `team` INT( 11 ) NOT NULL DEFAULT '0',
ADD `reputation` INT( 11 ) NOT NULL DEFAULT '0';
ALTER TABLE `monsters`
  DROP `exp1`,
  DROP `exp2`,
  DROP `credits1`,
  DROP `credits2`,
  DROP `lang`;
TRUNCATE TABLE `monsters`;
INSERT INTO `monsters` (`id`, `name`, `level`, `hp`, `agility`, `strength`, `speed`, `endurance`, `location`, `lootnames`, `lootchances`, `desc`, `resistance`, `dmgtype`) VALUES
(1, 'Szczur', 1, 4, 3.00, 3.00, 3.00, 3.00, 'Altara', '', '', 'Szczury, które można spotkać na Arenie Walk, wywodzą się od pospolitego <i>ratti norvegici</i> i mają podobne do niego nawyki żywieniowe, przez całe lata jednak były modyfikowane przez zespół gnomich przyrodników, któremu przewodził słynny badacz natury, Muddy Doodle, by uczynić z nich odpowiedniego przeciwnika do treningów.<br />\r\n<br />\r\nMimo niewielkich gabarytów, <i>rattus pugnandus</i> stanowi nie lada wyzwanie dla początkujących magów i wojowników. Tę – stosunkowo nową – odmianę szczura cechuje przede wszystkim niespotykana u jego kuzynów wytrzymałość oraz niezwykła inteligencja. Dzięki temu stworzenia owe potrafią na arenie przez bardzo długi czas utrzymać się przy życiu, bądź to unikając ataków, bądź też po prostu nic sobie z nich nie robiąc.<br />\r\n<br />\r\nPonadto szczury z Areny Walk w chwili zagrożenia zaczynają wydawać bardzo wysokie dźwięki, dzięki którym chcą zdezorientować przeciwnika. Zdarza się, że piski te powodują uszkodzenie błony bębenkowej trenującego, toteż bardzo ważne jest, by do walki zakładać hełm albo przynajmniej zatykać sobie uszy.<br />\r\n<br />\r\nMuddy Doodle tak mówił o efekcie prac jego zespołu:<br />\r\n<br />Cytat:<br /><i>„Mamy nadzieję, że w ten sposób młodzi będą mogli ćwiczyć bez niepotrzebnego narażania życia. Istnieje bardzo znikoma szansa, że nasze szczury kogokolwiek zabiją. Trzeba tu jednak zaznaczyć, że – wypuszczone na wolność – te gryzonie stanowiłyby ogromne zagrożenie dla społeczeństwa ze względu na ich niebywałą inteligencję. Już zwykłe szczury są kłopotliwe dla ludzi, cóż dopiero nasze ratti pugnandi!”</i><br />\r\n<br />\r\nStrażnicy miejscy zapewniają, że żaden zmodyfikowany szczur nie ma szansy wydostać się z pojemnika, w którym się je trzyma, jednakowoż mieszkańcy Altary są dość nieufnie nastawieni:<br />\r\n<br />Cytat:<br /><i>Szczury?! A bo to nam potrzeba więcej szczurów?! Już i tak ganiam za nimi całymi dniami z miotłą! Temu miastu nie potrzeba więcej tego plugastwa!</i> (karczmarka, 28 l.)', 'none;none', 'none'),
(2, 'Goblin', 2, 8, 5.00, 5.00, 5.00, 5.00, 'Altara', 'Kieł Goblina;Skóra Goblina;Pazur Goblina;Czaszka Goblina', '45;77;95;100', 'Gobliny są nieco niższe od ludzi i dużo szczuplejsze, z wyraźnie zaznaczonymi stawami i nie raz mocno sterczącym uzębieniem. W przeciwieństwie do pozostałych zielonoskórych, mają bardzo ostre pazury, stanowiące rekompensatę za mikrą posturę i niewielką siłę fizyczną. W walce zazwyczaj gryzą i zadają rany szarpane – zaraz po treningu należy zdezynfekować wszystkie skaleczenia, jako że gobliny roznoszą bardzo szeroki wachlarz chorób.<br />\r\n<br />\r\nDo niedawna uważano gobliny za kuzynów orków, etnolog Mad Doodle jednak wykazał w szeregu rozpraw naukowych, że pokrewieństwo to jest luźniejsze, niż przypuszczano. Gobliny więcej wspólnego mają z ludźmi. Ogromnym zaskoczeniem okazało się na przykład, że niekiedy parają się handlem. Najprawdopodobniej wiele osobników, które znalazły swój koniec na Arenie Walk, wbrew słowom Łowców nie zostało bohatersko pojmanych w dziczy, a sprzedanych przez goblińską starszyznę w zamian za skóry i narzędzia.<br />\r\n<br />\r\nMało kto wie, że gobliny dzielą się na trzy grupy: na Arenie spotkać można pospolite gobliny jaskiniowe, istnieje jednak klan bardzo sprytnych, podstępnych i inteligentnych „Stalodzierżców”, jak oni sami o sobie mówią, oraz – odznaczających się nieprzeciętną jak na ten gatunek siłą – goblinów Hob, niebezpiecznych samotników, zamieszkujących głównie górskie szczyty.<br />\r\n<br />\r\nŚwiadkowie relacjonują spotkania z tymi zielonoskórymi:<br />\r\n<br />Cytat:<br /><i>„Aye, odwiedził nas tu kiedyś taki jeden… Z tych cholernych Stalodzierżców. Nie cierpię ich. Przez te jego przeklęte wynalazki prawie połowa wsi poszła z dymem. Powinni go zaciągnąć za te wielkie uszy do lochu, ale uciekł, mynda jedna.”</i> (rolnik z okolic Altary, 58 l.)<br />\r\n<br />Cytat:<br /><i>„Hob gobliny? Nie, nigdy nie słyszałam. Tutaj w okolicy to tylko takie zwykłe żyją. A kto ich tam wie, czy w wioskach, czy w jaskiniach. Przeca ja tam ich nie odwiedzam. Obwieszają się kośćmi i machają patykami. Paskudne stworzenia. Jak to: skąd wiem? Na Arenie widziałam. No… nie no, właściwie nie wiem, czy faktycznie same się w te gnaty ubierają, czy przystraja je do walki mistrz ceremonii. Ale każdy wie, że to dzicz.”</i> (mieszkanka Altary, 34 l.)<br />\r\n<br />Cytat:<br /><i>Myślę, że opinie, które krążą o goblinach, są dla nich bardzo krzywdzące. Gobliny mogą być dla nas fantastycznym rynkiem zbytu, należałoby nawiązać z nimi kontakty handlowe. Jeśli nie ze wszystkimi, to przynajmniej ze Stalodzierżcami.</i> (kupiec Geldgier, 382 l.)', 'none;none', 'none'),
(3, 'Ork', 4, 16, 7.00, 7.00, 7.00, 7.00, 'Altara', 'Pazur Orka;Skóra Orka;Kość Orka;Czaszka Orka', '45;77;95;100', 'Nikt nie wie, jak tak naprawdę nazywają się orkowie. Miano, pod którym są nam znani, stanowi tylko uproszczoną transkrypcję odgłosu, jaki wydają dorosłe osobniki chcące zamanifestować swoją siłę – czy to przed resztą klanu, czy to przed wrogiem. Towarzyszy temu zazwyczaj uderzanie o ziemię tarczą lub przynajmniej tupanie. Również ich strój – zazwyczaj powiązane byle jak strzępy odzienia ich ofiar, wielekroć ozdobione czaszkami – służy obniżeniu morale przeciwnika.<br />\r\n<br />\r\nOrkowie są masywni i dysponują ogromną siłą fizyczną. Ich słabą stronę stanowi natomiast głupota. Nie potrafią posługiwać się żadnym rodzajem broni bardziej skomplikowanej od topora bojowego, nie mają też pazurów, kły zaś służą jedynie ustaleniu hierarchii w klanie – nie używają ich w walce. <br />\r\n<br />\r\nKultura orków przez całe wieki była owiana tajemnicą. Dopiero śmiała misja Glummy’ego Doodle’a pozwoliła poznać nieco zwyczaje tego niebezpiecznego gatunku. Glummy, pojmawszy młodego, wchodzącego dopiero w dorosłość orka, zdołał go udomowić i nauczyć czytania i pisania. Przy tej okazji zresztą wyszło na jaw, że orkowie mają bardzo słaby wzrok. Nim Glummy zginął śmiercią tragiczną, zmiażdżony przez ciśnięty z dużą siłą dyliżans pocztowy, sporządził obszerne sprawozdanie ze swoich sesji z Ballcrusherem:<br />\r\n<br />Cytat:<br /><i><b>Dzień 5.</b><br />\r\nObiekt wreszcie przestał rzucać odchodami. Myślę, że w końcu uda nam się podać mu jakieś jedzenie. Nie chcę, żeby padł z głodu.<br />\r\n<br />\r\n<b>Dzień 6.</b><br />\r\nNie, jednak nie przestał. Chciał zmylić naszą czujność. Bestie są bardziej cwane, niż dotąd myśleliśmy.<br />\r\n<br />\r\n<b>Dzień 7.</b><br />\r\n<u>Do zapamiętania</u>: nie karmić orka mlekiem i ogórkami.<br />\r\n<br />\r\n(…)<br />\r\n<br />\r\n<b>Dzień 28.</b><br />\r\nWidać postępy. Faszerowanie naparem z illanias przynosi pożądany efekt. Uspokojonego orka można przebadać. Staramy się wzbudzić w nim zainteresowanie naszą kulturą, żeby sam zapragnął nauczyć się czytać. Trochę nam przeszkadza senność obiektu. Może będzie trzeba podawać mniej ziółek.<br />\r\n<br />\r\n<b>Dzień 32.</b><br />\r\nWracamy do poprzedniej dawki illanias. Mam złamaną rękę i zmiażdżony nos. Żuchwa powoli się zrasta.<br />\r\n<br />\r\n(…)<br />\r\n<br />\r\n<b>Dzień 78.</b><br />\r\nUdało się! Ork zaczął dziś naukę!<br />\r\n<br />\r\n(…)<br />\r\n<br />\r\n<b>Dzień 239.</b><br />\r\nTAK! TAK!!! Opanowaliśmy literę „A”!!! Idę się upić z radości.<br />\r\n<br />\r\n<b>Dzień 240.</b><br />\r\nKac-gigant.<br />\r\n<br />\r\n(…)<br />\r\n<br />\r\n<b>Dzień 1625.</b><br />\r\nObiekt nazywa się Ballcrusher. Opowiedział mi, w jaki sposób zdobył to imię, ale nie chcę o tym pisać… W klanie był wojownikiem. Oprócz wojowników, każdy klan ma też bardzo wpływową kastę szamanów i, jeśli dobrze zrozumiałem, starszyznę, która ma władzę sądowniczą. Orkowie darzą ogromnym szacunkiem przyrodę, wierząc, że każdy obiekt ma swojego ducha opiekuńczego. Szamani potrafią wzywać te duchy i nakłaniać do pomocy. Jutro spróbuję się dowiedzieć, co tak naprawdę oznacza słowo „ork” i jak w rzeczywistości nazywa się ten gatunek. To może być odkrycie większe, niż zbudowanie Astralnej Machiny!<br />\r\n<br />\r\n<b>Dzień 1626.</b> (innym, bardzo koślawym charakterem pisma)<br />\r\nPAN ROZPŁASZCZONY! JEGO MAGICZNE KULE JA ZAWIESZA SOBIE NA SZYJA! JA WRACA DO KLAN! ORK! ORK! ORK!</i>', 'none;none', 'none'),
(4, 'Szczurołak', 7, 28, 12.00, 17.00, 17.00, 12.00, 'Altara', 'Ząb Szczurołaka;Futro Szczurołaka;Pazur Szczurołaka;Ogon Szczurołaka', '45;77;95;100', 'O pochodzeniu szczurołaków niewiele wiadomo, ale powszechnie uważa się, że dużo taśmy klejącej zużyto, nim udało się stworzyć nowy gatunek.<br />\r\n<br />\r\nWzrost szczurołaków waha się między metrem a półtora metra. Sylwetkę mają raczej gruszkowatą, a do tego długi, łysy, chwytny ogon oraz szarą bądź brązową, krótką sierść. Ze względu na niezbyt imponujący wygląd, często bywają niedoceniane jako przeciwnicy na arenie, podczas gdy zdolnościami bojowymi przewyższają orków. Co prawda nie dysponują zbyt dużą siłą, w dodatku są niebywale tchórzliwe, tym niemniej ponadprzeciętny spryt pozwala tym stworzeniom na długie stawianie oporu. Szczurołaki używają halucynogennych pyłków, wytwarzanych przez nich z grzybów hodowanych w kanałach, potrafią posługiwać się też bronią tnącą i miotającą.<br />\r\nPodobnie jak gobliny, szczurołaki roznoszą mnogość chorób, na które one same są odporne.<br />\r\n<br />\r\nTak naprawdę bardzo trudno skłonić szczurołaka do walki. Schwytane w kanałach i przetransportowane na Arenę, zazwyczaj chętniej proponują przeciwnikom umowy handlowe, wysokie stanowiska w swoim panteonie (ubóstwienie żyjącej istoty to wśród szczurołaków bardzo powszechna praktyka) lub usiłują wzbudzić litość, zwijając się w kulkę i żałośnie piszcząc.<br />\r\n<br />\r\nSzczurołaki są jednymi z najbardziej znienawidzonych stworzeń w Altarze.<br />\r\n<br />Cytat:<br /><i>Szczurołaki? Że niby pół-ludzie, pół-szczury? Dużo taśmy klejącej musieli zużyć, no nie? He, he, he…</i> (górnik z Kazad-nar, 92 l.)<br />\r\n<br />Cytat:<br /><i>Co takiego?! A żeby mi tu w pobliżu nogi nie postawiły?! Bo jak przegonię, to futro bydzie latać po całej Altarze! Won mi z takim wynaturzeniem! Ludzie-szczury… Co za pomysł! Nawet Tartus by na coś takiego nie mógł patrzeć! … Zresztą… Ludzie-szczury? Jak to miałoby w ogóle powstać…? Że niby oni tak te szczury, he, he, he, taśmą, no wiesz…?</i> (zielarka Pansy, 189 l.)<br />\r\n<br />\r\nSame szczurołaki jednak nie przejmują się złą sławą. Są przekonane o wyższości ich gatunku:<br />\r\n<br />Cytat:<br /><i>Och, to oczywiste, tak, oczywiste. Kiedy Wielki Zębaty zaprosi nas do Przedwiecznej Piwnicy, żaden obcy nie będzie tam miał wstępu, o nie, nie będzie miał. Jesteśmy wybrani, tak. A że nas łapią i rzucają na Arenę? To przejściowe trudności, o tak, przejściowe. Zobaczycie, wszyscy zobaczycie. Ludzie, niziołki, plugawe krasnoludy… nikt nie trwa wiecznie. My trwamy, tak, trwamy. Wielki Zębaty rozkruszy kiedyś Cuchnącego Grzyba. Wtedy wszyscy zobaczycie, tak!</i> (Nool, kapłan Wielkiego Zębatego)<br />\r\n<br />\r\nMało istnieje rycin przedstawiających szczurołaki – w kronikach najczęściej pojawia się jedna, o której mówi się, że jest karykaturą. Choć księgi wspominają, że jeszcze nim stworzenia te zeszły do kanałów, tak właśnie wyglądały.<br />\r\n<a href=images/szczurolak.jpg target=_blank>Starożytna rycina przedstawiająca Szczurołaka</a>', 'none;none', 'none'),
(5, 'Gwardzista', 10, 40, 21.00, 21.00, 21.00, 21.00, 'Altara', 'Kość Gwardzisty;Czaszka Gwardzisty;Palec Gwardzisty;Serce Gwardzisty', '45;77;95;100', '<br />Cytat:<br /><i>Bez komentarza.</i> (Gotfryd, dowódca Gwardii Królewskiej)<br />\r\n<br />Cytat:<br /><i>Gwardziści, psia ich mać… Banda rozbójników. Gorsi, niż ci co napadają karawany w górach. Bandyci na garnuszku króla… W kupie mocni, ale żebym ja tak dorwał jednego… Ja i moja patelnia…!</i> (Gippo, kucharz, 56 l.)<br />\r\n<br />\r\nPowołanie Gwardii Królewskiej ginie w mrokach niepamięci. Jedni mówią, że król Thindil, wbrew ustaleniom duumwiratu, zgromadził wokół siebie zbrojną drużynę, by z czasem zwiększyć swoje wpływy i zostać jedynowładcą. Inni zaś twierdzą, iż zamachu stanu próbował dokonać drugi duumwir, Cordescu, ale – dowiedziawszy się o tym – Thindil przekupił dowódcę gwardii, wskutek czego gwardziści wyeliminowali samego Cordescu. Władca nie rozpuścił nowopowstałego oddziału, by zawsze mieć w odwodzie wykwalifikowanych żołnierzy.<br />\r\n<br />\r\nNiezależnie jednak od najdawniejszej historii, sława zawsze wyprzedzała królewskich gwardzistów. Słynęli oni jako ludzie o stalowej skórze i mięśniach z adamantium. Ponoć potrafili gołymi rękami zatrzymać lecącą strzałę, a najeźdźców słyszeli z odległości wielu staj. Nie rozmawiali z nikim poza władcą.<br />\r\n<br />\r\nI, jak to często bywa w takich przypadkach, coraz więcej pojawiało się osób, które chciały sprawdzić, ile prawdy kryje się za tymi plotkami.<br />\r\nA kryło się jej niewiele.<br />\r\nGwardziści prędko stracili status żywej legendy. Część z nich, nie mogąc odnaleźć się w nowej rzeczywistości, w której byli wyśmiewani, obrzucani pomidorami i wielekroć układano o nich sprośne wierszyki, występowała z Gwardii Królewskiej, by szukać szczęścia na piasku Areny.<br />\r\n<br />\r\nOkazało się zresztą, że choć pierwotne plotki były mocno przesadzone, straży przybocznej króla nie należy jednak lekceważyć. Niejeden hardy wojownik, a nawet mag, poległ od miecza gwardzisty – i, trzeba przyznać, nie tylko od miecza, zdarzały się też bowiem ukryte w rękawach sztylety, podstępne kopniaki w rzepkę czy sypanie w oczy piaskiem z solą. To właśnie kontrowersyjne metody prowadzenia walki sprawiły, że gwardziści obecnie nie cieszą się sympatią obywateli i są postrzegani raczej jako bandyci, niż niegdysiejsi elitarni strażnicy Jego Królewskiej Mości.', 'none;none', 'none'),
(6, 'Troll', 14, 56, 27.00, 37.00, 27.00, 37.00, 'Altara', 'Pazur Trolla;Skóra Trolla;Kieł Trolla;Czaszka Trolla', '45;77;95;100', 'Trolle kojarzą się głównie z twardoskórymi olbrzymami o intelekcie grzebienia – jest to jednakże opinia bardzo dla nich krzywdząca. Jako istoty prawdziwie długowieczne (mówi się, że trolle mają tylko jedno pokolenie, które trwa od początku świata po dziś dzień) miały dość czasu wolnego, by nabrać nieco ogłady i zdobyć wykształcenie. Wedle najnowszych badań, prowadzonych przez słynnego archeologa Rocky’ego Doodle’a, trolle w istocie u zarania dziejów nie należały do szczególnie błyskotliwych stworzeń, ale niesłychana wytrzymałość fizyczna umożliwiła im przetrwanie. Z czasem jednak objętość ich mózgów stawała się coraz większa, toteż dzisiejsi przedstawiciele tego gatunku potrafią biegle posługiwać się nawet sześcioma językami (z których zazwyczaj co najmniej połowa staje się językami wymarłymi, zanim troll opanuje je do końca), świetnie radzą sobie z każdym typem broni, a także pojęły w trakcie ewolucji jedno: dobry wróg to wróg, który ma innego wroga. I to ta ostatnia cecha sprawiła, że walki z trollami na Arenie cieszą się takim zainteresowaniem widowni.<br />\r\nZazwyczaj na te pojedynki przybywają nawet przedstawiciele prasy, a następnego dnia relacje figurują na pierwszych stronach gazet.<br />\r\n<br />\r\n<br />Cytat:<br /><i>Proszę państwa, powitajmy brawami kolejnego śmiałka, który chce skrzyżować miecze z potężnym Zankischem! Co za mięśnie ma nasz troll! Jaki szeroki uśmiech! Jaki pewny siebie! Chyba ma dzisiaj dobry dzień!<br />\r\n<br />\r\nTAK! Zwarli się w śmiertelnym uścis… Zankisch odepchnął przeciwnika i trzyma dystans… Coś powiedział – wojownik opuścił miecz i odpowiada… No i przepadł! Widownia rzuca chlebem, wykrzykując „Nie karm trolla, bucu!”, ale to nic nie daje! Śmiałek poczerwieniał i ewidentnie zaczął dyskutować z Zankischem. Nie słyszę stąd, co mówią, ale wojownik jest coraz bardziej podenerwowany. I JEST! Jest to, na co wszyscy czekali! Ktoś z pierwszych rzędów dołączył do kłótni! Cóż to się dzieje! Zaraz dojdzie do rękoczynów! Troll obserwuje… wyczuł, że emocje opadają, bo znów coś powiedział. Na arenę zeszło kilku obywateli i wykłócają się, gorączkowo gestykulując.<br />\r\n<br />\r\nTak jest, proszę państwa. Troll znów przechytrzył przeciwnika. Odchodzi pod eskortą straży, zaśmiewając się do rozpuku, podczas gdy na arenie coraz więcej osób sięga po broń.<br />\r\n<br />\r\nZ Areny Walk w Altarze mówił dla państwa Bilker Crook.</i> (relacja na żywo z jednej z walk)', 'none;none', 'none'),
(7, 'Ogr', 18, 72, 36.00, 49.00, 15.00, 49.00, 'Altara', 'Kieł Ogra;Skóra Ogra;Pazur Ogra;Czaszka Ogra', '45;77;95;100', '', 'none;none', 'none'),
(8, 'Orog', 22, 88, 56.00, 56.00, 56.00, 56.00, 'Altara', 'Kieł Oroga;Futro Oroga;Pazur Oroga;Krew Oroga', '45;77;95;100', '', 'none;none', 'none'),
(9, 'Szkielet', 26, 104, 79.00, 65.00, 79.00, 65.00, 'Altara', 'Kość Szkieleta;Czaszka Szkieleta;Ząb Szkieleta;Korpus Szkieleta', '45;77;95;100', '', 'none;none', 'none'),
(10, 'Gigantyczny Pająk', 30, 156, 91.00, 108.00, 91.00, 108.00, 'Altara', 'Odnóża Gigantycznego Pająka;Odwłok Gigantycznego Pająka;Szczękoczułki Gigantycznego Pająka;Gruczoł Jadowy Gigantycznego Pająka', '45;77;95;100', 'O pochodzeniu Gigantycznego Pająka krąży wiele legend. Jedna mówi o straszliwym czarnoksiężniku, który rzucił zaklęcie powiększające na pająka, aby wysłać go w akcie zemsty do jednego ze swoich wrogów. Inne podanie opowiada o nierozważnym alchemiku, który zostawił otwarty eliksir nieznanego przeznacenie, do którego weszły małe pajączki, przez co zostały zmutowane i wyrosły na naprawdę wielkie okazy. Jednak ludzie uważają, że Gigantyczne Pająki pochodzą wprost od samego diabła, że są jego jednym z gorszych wytworów. <br />\r\n<br />\r\nGigantyczny Pająk występuje najczęściej w podziemiach i katakumbach, by tam w ciemności czyhać na swoje ofiary.<br />\r\n<br />\r\nNiestety niewiele wiemy o wyglądzie Pająka, ponieważ mało kto uszedł z życiem po spotkaniu z nimi. Domyślać się można, że wyglądają jak pająki, tylko są ze sto razy większe. A w powiększeniu wszystko wygląda gorzej.<br />\r\n<br />\r\n-Tak...Jam widział takiego pająka. Ledwo żem uszedł życiem! Uratowało mnie tylko, to że oblałem go trunkiem z mojej piersióweczki, nawiasem mówiąc, dobry trunek to był. Chlusnąłem mu w ślipia i ten potwór nie wiedział, co jest grane. A ślipia... Ślipia to miał większe niż talerz, z którego co dzień wżeram obiad. Wziąłem tyłek w troki i zwiałem jak najszybciej się da! - opowiada nam emerytowany strażnik z pewną nutą dumy w głosie.<br />\r\n<br />\r\n-On by-by-był na-na-naprawdę stra-straszny. Ogr-ogrooomny pająk! - relacjonuje przestraszony młodzik, który widział pająka z daleka w miejskich katakumbach. ', 'earth;weak', 'earth'),
(11, 'Bezgłowy Rycerz', 35, 168, 117.00, 134.00, 134.00, 117.00, 'Altara', 'Kość Bezgłowego Rycerza;Czaszka Bezgłowego Rycerza;Serce Bezgłowego Rycerza;Głowa Bezgłowego Rycerza', '45;77;95;100', 'Podobno ten rycerzyk to niejedną damę zbałamucił! te rysy twarzy, piwne oczy otulone firanką długich, gęstych rzęs... Prosty, arystokratyczny nos, zalotnie usta wycięte, jakby do całowania stworzone... Panny mdlały na jego widok, niektóre piszczały, a innym to podobno dech w piersi zapierało! Bożyszcze na dwóch nogach! A historyje o nim jakie chodzą...<br />\r\n<br />\r\n<b>Pani Piwonia</b>, matrona zacna, co to jej cyc w okolicy znany i lubiany, takoż rzecze: <br />\r\n<br />\r\n<i>  - jak żem młoda była... młodsza znaczy, młodsza... no tego... to ja żem go widziała! och, jak żem ja go widziała! caluśkiego, jak bogowie go stworzyli, a jakiego on miał ptoka! takiego ptoka to każdy chłop ino chciałby... znaczy nie ptoka... ten no... intelekt! ta, intelekta miał takiego wielgachnego, co to nim na pół mógł babę przesiekać.... Piękne to czasy były, zaiste, piękne... </i> <br />\r\n<br />\r\nZ kolei <b>Gertruda</b>, co to teraz królewskie gacie pierze i w zamkowej kuchni niepodzielne rządy sprawuje tak owego rycerza wspomina:<br />\r\n<br />\r\n<i>  - no, widzieć to jo go nie widziała, ale jak żem chyża była, młódka taka nieopierzona, co to za każdym fiu... tym no, MENSZCZYZNĄ! się oglądała, jak to na pinkną krasnoludzicę przystało, to ja się za nim rozglądałam! oj jak ja żem się rozglądała, aż mi ślepia tak biegały, od prawa do lewa! bo to takie słuchy chodziły, że na samą myśl, to babom się ino w galotach woda zbierała! oj, żebym to ja młodsza była.... sama bym go szukać lazła, bo ta głowa to nie ważna przeca... a tero to tylko Król pozostał. No i gacie... Biedna ja </i><br />\r\n<br />\r\n<br />\r\nTak to kiedyś podobno było. Później jakiś zazdrosny mąż, co to żonkę zadowolić nie mógł i ta pocieszenia w ramionach (i nie tylko) innego poszukała łeb rycerzowi odciął, solą posypał, rytuały magiczne jakieś odprawił i nieszczęśnika w niepoświęconej ziemi pochował.<br />\r\nTen po trzech dniach się wykopał, wkurzony wielce, i dalo w świat, głowy szukać. Bo ta się gdzieś w tym całym rozgardiaszu zapodziała. I jak na wkurzonego rycerza przystało, energia go rozpiera, dziewice (i te bardziej używane również - rycerz wszak nikogo nie faworyzuje) bałamuci, chłopów morduje, kozy kradnie... no i głowy szuka, po krainie łażąc. ', 'earth;weak', 'earth'),
(12, 'Ghoul', 40, 192, 150.00, 170.00, 150.00, 170.00, 'Altara', 'Kieł Ghoula;Skóra Ghoula;Pazur Ghoula;Szpik Ghoula', '45;77;95;100', '', 'wind;weak', 'wind'),
(13, 'Nekromanta', 45, 234, 189.00, 212.00, 212.00, 189.00, 'Altara', 'Pazur Nekromanty;Kość Nekromanty;Czaszka Nekromanty;Pancerz Nekromanty', '45;77;95;100', '', 'fire;strong', 'fire'),
(14, 'Wilkołak', 50, 260, 228.00, 253.00, 253.00, 228.00, 'Altara', 'Kieł Wilkołaka;Futro Wilkołaka;Krew Wilkołaka;Pysk Wilkołaka', '45;77;95;100', '', 'water;medium', 'water'),
(15, 'Wampir', 55, 260, 270.00, 270.00, 245.00, 245.00, 'Altara', 'Popiół z Wampira;Kość Wampira;Kieł Wampira;Krew Wampira', '45;77;95;100', '', 'wind;strong', 'wind'),
(16, 'Lassaukaur', 60, 288, 311.00, 284.00, 311.00, 284.00, 'Altara', '', '', '', 'earth;weak', 'earth'),
(17, 'Obserwator', 65, 312, 338.00, 338.00, 338.00, 338.00, 'Altara', '', '', '', 'none;none', 'none'),
(18, 'Golem', 70, 336, 372.00, 403.00, 372.00, 403.00, 'Altara', '', '', '', 'earth;strong', 'earth'),
(19, 'Żywiołak Powietrza', 75, 390, 425.00, 459.00, 459.00, 425.00, 'Altara', '', '', '', 'wind;strong', 'wind'),
(20, 'Żywiołak Wody', 80, 448, 440.00, 440.00, 440.00, 440.00, 'Altara', '', '', '', 'water;strong', 'water'),
(21, 'Żywiołak Ziemi', 85, 476, 498.00, 464.00, 498.00, 464.00, 'Altara', '', '', '', 'earth;strong', 'earth'),
(22, 'Żywiołak Ognia', 90, 504, 502.00, 538.00, 538.00, 502.00, 'Altara', '', '', '', 'fire;strong', 'fire'),
(23, 'Troll Górski', 95, 570, 542.00, 580.00, 542.00, 580.00, 'Altara', '', '', '<i> Na temat Górskich Trolli krąży wiele historii, niektóre są nawet opisane i dostępne w miejskiej bibliotece. Podobno kiedyś ktoś Górskiego Trolla spotkał i przeżył. Trudno jednak stwierdzić, czy jest to prawdą, gdyż ów "szczęśliwiec" nie pożył zbyt długo, i choć opowiadał jakoby ów Troll zaskoczył go podczas przeprawy przez most w górach, i choć historia ta była dość wiarygodna, to jednak stan umysłu owego delikwenta sprawiał, że należy na tą opowieść zapatrywać się dość sceptycznie. Szczęśliwiec owy, po powrocie do miasta trafił w ręce medyków, uzdrowicieli i wszelakiej maści boskich wysłanników, którzy chorobę i złego ducha próbowali z niego wypędzić. Owe próby zakończyły się tym, że nasz poszukiwacz przygód pianę z ust zaczął toczyć, szczać w majtole w ilościach iście rekordowych i bąki puszczać o zasięgu niemal nieograniczonym. Ale historię o trollu nadal powtarzał, na wszystkich bogów zapewniając, że jest ona prawdziwa. Więc ją przytoczymy, gdyż jak na razie jest to najbardziej wiarygodne źródło, jakie mamy.</i><br />\r\n<br />\r\n<br />\r\n<b>Alojzy Dojak </b>, mąż stateczny, prawy i odważny.... prawdę mówiąc nierób i obibok, któremu znudziło się ugniatanie dupska w glinianej lepiance, comiesięczne bara bara z brzydką żoną i codzienny ryk szóstki bachorów, których zdołał się dorobić, ale o tym wspominać nie wypada... postanowił przygody zaznać. W tobołek wikt wpakował, trunku przedniego, co by w drodze się wzmocnić, miecz jakiś do pasa przywdział i w góry wyruszył. Wędrował długo. Wiedział, że długo, bo trunek się kończył. Zmierzchało już, gdy wędrówkę mu przerwał ogromny głaz, toczący się ze szczytu góry. Kilkanaście metrów dalej ujrzał Wielką kamienną poczwarę, z łapami jak taczki, nogami jak pniem drzew i mordą niebezpiecznie podobną do twarzy jego kochanej małżonki. Ani chybi, Troll! I to kamienny, bo poszarzały jakiś taki i z lekka chropowaty. Pierwowzór jego ukochanej żoneczki nawet z charakteru był do niej podobny, bo ryczeć zaczął wniebogłosy i kolejnymi kamieniami ciskać w biednego Alojzego. Ten – jak na znawcę kobiecej natury przystało, gdyż z założenia wyszedł, że to przeca kobieta być musi, do  żony podoba i wrzeszczy jak diabli, ani chybi kobieta! – o mieczu przy pasie zapomniał, tobołek na ziemię rzucił i wrzeszcząc co sił w płucach <i> „Nie poruchasz, babsztylu!” </i> w dół zbocza się rzucił, gnając, jakby go stado wilków goniło. <br />\r\n<br />\r\n<br />\r\n<i> Później okazało się, że w głowę dostać musiał kilkakrotnie, stąd może to bełkotanie… choć żona mówi, że on zawsze był taki i zmiany nie dostrzega. </i><br />\r\n', 'earth;medium', 'earth'),
(24, 'Centaur', 100, 560, 620.00, 620.00, 580.00, 580.00, 'Altara', '', '', '', 'none;none', 'none'),
(25, 'Gliniany Golem', 105, 588, 620.00, 662.00, 620.00, 662.00, 'Altara', '', '', '', 'earth;weak', 'earth'),
(26, 'Kamienny Golem', 110, 616, 702.00, 658.00, 702.00, 658.00, 'Altara', '', '', '', 'earth;strong', 'earth'),
(27, 'Brązowy Golem', 115, 644, 744.00, 698.00, 744.00, 698.00, 'Altara', '', '', '', 'fire;weak', 'fire'),
(28, 'Żelazny Golem', 120, 672, 784.00, 784.00, 736.00, 736.00, 'Altara', '', '', '', 'fire;medium', 'fire'),
(29, 'Piekielny Pies', 125, 750, 776.00, 826.00, 776.00, 826.00, 'Altara', '', '', 'Widzisz przyjacielu, to nie takie proste. Coś dzwoniło, ale nie wiadomo w której świątyni. Dziś ludzie o tym nie pamiętają, zapominają powoli... Tylko nieliczne stare dziady, takie jak ja coś tam pamiętają. A ja wtedy tam byłem, i wszystko widziałem. Co do tego ma moja ręka? Widzisz, ręce są dla wojownika wszystkim. W nich jest kunszt, wiedza, doświadczenie. A dziś nie mogę nią utrzymać kubka...<br />\r\nByło nas dwudziestu, chłopy na schwał. I do wypitki, i do wybitki. Znaliśmy się dobrze, służyłem w Gwardii już od kilku lat. Skierowano nas do strażnicy u podnóża Kazad-Nar. Coś poszarpało poprzednich strażników i paru górników. Nie chcieli w góry wychodzić, ustały dostawy mithrilu... trzeba było coś z tym zrobić.<br />\r\n<br />\r\nPrzez pierwsze dni nic się nie działo. Nie znaleźliśmy nic podejrzanego. Później jednak dotarło do nas, że wszędzie jest niesamowicie cicho... jakby kto makiem zasiał. Żadnego ptaka, dźwięku - nic. Nastrój był ponury, wszyscy spoważnieli. Tego samego wieczora wysłali mnie na obejście. Po chwili dotarł do moich uszu straszny, mrożący krew w żyłach wrzask towarzyszy. Odwróciłem się jak oparzony w stronę posterunku, i wtedy go zobaczyłem. Wyglądał zupełnie jak wilk, nie było jednak na nim ani piędzi ciała - same kości, pokryte czymś, co wyglądało jak łuski. Tak, łuski... takie jak u węża. Biło od niego zło - po prostu się czuło całym ciałem, że to plugawy stwór. Rozwarł pysk i skoczył, a ja zasłoniłem się ręką - jego kły zatopiły się w moim przedramieniu. Ból był straszny, przenikliwy, jakby kto wbił mi rozżarzone gwoździe w rękę. Paliło. Odgłosy walki w obozie dochodziły do mnie jakby zza ściany. Dobyłem miecza i ciąłem go w pysk. Raz, drugi, trzeci - czerwony blask w jego oczodołach przygasł, potwór przewrócił się na ziemię. Ból w ręce eksplodował, o mało nie straciłem przytomności. Znów zapadła cisza, którą po chwili przerwało przeciągłe wycie bestii. Spojrzałem na swoją rękę - karwasz był przegryziony i osmalony. Ruszyłem w kierunku strażnicy. Już po chwili zauważyłem, że płonęła. Wokół leżało kilka ścierw potworów oraz moi towarzysze broni, straszliwie okaleczeni. Krzyknąłem, ale nikt mi nie odpowiedział. Straciłem przytomność. Ocknąłem się po wielu godzinach w osadzie. Już nie mogłem powrócić do służby. Przysłano kolejne oddziały. Po pewnym czasie bestie odeszły, ale kiedyś wrócą. Jestem tego pewien...', 'fire;strong', 'fire'),
(30, 'Sukkub', 130, 832, 814.00, 866.00, 866.00, 814.00, 'Altara', '', '', '', 'fire;medium', 'fire'),
(31, 'Widmowy Pies', 135, 918, 908.00, 854.00, 908.00, 854.00, 'Altara', '', '', '', 'none;none', 'none'),
(32, 'Dżin', 140, 896, 920.00, 920.00, 920.00, 920.00, 'Altara', '', '', '', 'wind;medium', 'wind'),
(33, 'Smoczy żuk', 145, 928, 932.00, 990.00, 932.00, 990.00, 'Altara', '', '', '', 'none;none', 'none'),
(34, 'Przeklęty Wojownik', 150, 1020, 970.00, 1030.00, 1030.00, 970.00, 'Altara', '', '', '', 'none;none', 'none'),
(35, 'Ekkimu', 155, 1054, 1010.00, 1072.00, 1010.00, 1072.00, 'Altara', '', '', '', 'water;medium', 'water'),
(36, 'Czarny Jednorożec', 160, 1088, 1048.00, 1112.00, 1048.00, 1112.00, 'Altara', '', '', '', 'none;none', 'none'),
(37, 'Lich', 165, 1122, 1088.00, 1154.00, 1088.00, 1154.00, 'Altara', '', '', '', 'fire;strong', 'fire'),
(38, 'Mroczne Widmo', 170, 1088, 1194.00, 1126.00, 1194.00, 1126.00, 'Altara', '', '', '', 'none;none', 'none'),
(39, 'Alaghi', 175, 1190, 1166.00, 1236.00, 1166.00, 1236.00, 'Altara', '', '', '', 'none;none', 'none'),
(40, 'Kyton', 180, 1296, 1240.00, 1240.00, 1240.00, 1240.00, 'Altara', '', '', '', 'none;none', 'none'),
(41, 'Salamandra', 185, 1332, 1244.00, 1318.00, 1244.00, 1318.00, 'Altara', '', '', '', 'fire;strong', 'fire'),
(42, 'Vintaru', 190, 1368, 1340.00, 1340.00, 1340.00, 1340.00, 'Altara', '', '', '', 'none;none', 'none'),
(43, 'Hydra', 195, 1404, 1362.00, 1440.00, 1362.00, 1440.00, 'Altara', '', '', '', 'water;strong', 'water'),
(44, 'Mimik', 200, 1520, 1420.00, 1500.00, 1500.00, 1420.00, 'Altara', '', '', '', 'none;none', 'none'),
(45, 'Sfinks', 205, 1558, 1520.00, 1520.00, 1520.00, 1520.00, 'Altara', '', '', '', 'earth;strong', 'earth'),
(46, 'Feniks', 210, 1596, 1538.00, 1622.00, 1538.00, 1622.00, 'Altara', '', '', '', 'none;none', 'none'),
(47, 'Cyklop', 215, 1548, 1598.00, 1684.00, 1684.00, 1598.00, 'Altara', '', '', 'Cyklop, mityczne stworzenie zamieszkujące górskie tereny, trudno dostępne dla człowieka. Blisko spokrewniony z Gigantem, dlatego współdzielą wiele legend na swój temat. Rękom Cyklopów przypisuje się budowę najznamienitszych, monumentalnych budowli w pobliżu i w samych górach Khazad-Nar, ale nie tylko. Prawdziwość tych opowieści jest poddawana w wątpliwość, ze względu na niski poziom rozwoju cywilizacyjnego tych stworzeń. Z drugiej strony, to nie do wiary, by tak ogromne budowle mogły wznieść istoty o wzroście elfa. <br />\r\nCyklop to humanoid, wysoki na 4 do 5.5 metra, przeważnie dobrze zbudowany. Oprócz rozmiarów, od człowieka odróżnia go znikome owłosienie na ciele oraz tylko jedno oko, na środku twarzy. ', 'none;none', 'none'),
(48, 'Gigant', 220, 1672, 1656.00, 1744.00, 1656.00, 1744.00, 'Altara', '', '', '', 'earth;strong', 'earth'),
(49, 'Tytan', 225, 1710, 1760.00, 1760.00, 1760.00, 1760.00, 'Altara', '', '', '', 'earth;strong', 'earth'),
(50, 'Jabberwock', 230, 1840, 1840.00, 1840.00, 1840.00, 1840.00, 'Altara', '', '', '', 'none;none', 'none'),
(51, 'Dracolich', 235, 1920, 1920.00, 1920.00, 1920.00, 1920.00, 'Altara', '', '', '', 'fire;strong', 'fire'),
(52, 'Bagienny Smok', 240, 2000, 2000.00, 2000.00, 2000.00, 2000.00, 'Altara', '', '', '', 'earth;medium', 'earth'),
(53, 'Lodowy Smok', 245, 2080, 2080.00, 2080.00, 2080.00, 2080.00, 'Altara', '', '', '', 'water;strong', 'water'),
(54, 'Widmowy Smok', 250, 2200, 2200.00, 2200.00, 2200.00, 2200.00, 'Altara', '', '', '', 'none;none', 'none'),
(55, 'Mroczny Paladyn', 260, 2400, 2400.00, 2400.00, 2400.00, 2400.00, 'Altara', '', '', '', 'wind;strong', 'wind'),
(56, 'Szablozębna Łasica', 1, 4, 3.00, 3.00, 3.00, 3.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(57, 'Płaskostopy Kobold', 2, 8, 5.00, 5.00, 5.00, 5.00, 'Ardulith', 'Kieł Kobolda;Skóra Kobolda;Pazur Kobolda;Czaszka Kobolda', '45;77;95;100', '', 'none;none', 'none'),
(58, 'Szerokonosy Goblin', 4, 16, 7.00, 7.00, 7.00, 7.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(59, 'Wysoki Hobogoblin', 7, 28, 14.00, 14.00, 14.00, 14.00, 'Ardulith', 'Kieł Hobogoblina;Skóra Hobogoblina;Pazur Hobogoblina;Czaszka Hobogoblina', '45;77;95;100', '', 'none;none', 'none'),
(60, 'Leśny Wąż', 10, 40, 25.00, 25.00, 18.00, 18.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(61, 'Chaotyczny Chochlik', 14, 56, 37.00, 27.00, 37.00, 27.00, 'Ardulith', 'Kość Chochlika;Czaszka Chochlika;Palec Chochlika;Serce Chochlika', '45;77;95;100', '', 'none;none', 'none'),
(62, 'Gnoll Łupieżca', 18, 72, 42.00, 42.00, 42.00, 42.00, 'Ardulith', 'Kość Gnolla;Czaszka Gnolla;Palec Gnolla;Serce Gnolla', '45;77;95;100', '', 'none;none', 'none'),
(63, 'Zielony Ork', 22, 88, 56.00, 56.00, 56.00, 56.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(64, 'Ostrokły Krenshar', 26, 104, 65.00, 79.00, 79.00, 65.00, 'Ardulith', 'Kieł Krenshara;Furto Krenshara;Pazur Krenshara;Krew Krenshara', '45;77;95;100', '', 'none;none', 'none'),
(65, 'Baśniowy Pseudosmok', 30, 156, 91.00, 108.00, 91.00, 108.00, 'Ardulith', 'Skrzydło Pseudosmoka;Czaszka Pseudosmoka;Pazur Pseudosmoka;Skóra Pseudosmoka', '45;77;95;100', '', 'wind;weak', 'wind'),
(66, 'Nocny Wilk', 35, 168, 117.00, 143.00, 143.00, 117.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(67, 'Leśny Gepard', 40, 192, 170.00, 150.00, 170.00, 150.00, 'Ardulith', 'Kieł Geparda;Skóra Geparda;Ogon Geparda;Czaszka Geparda', '45;77;95;100', '', 'none;none', 'none'),
(68, 'Ziemny Mefit', 45, 234, 189.00, 212.00, 212.00, 189.00, 'Ardulith', 'Esencja Mefita;Skrzydło Mefita;Skóra Mefita;Czaszka Mefita', '45;77;95;100', '', 'earth;strong', 'earth'),
(69, 'Pierścieniowy Lampart', 50, 240, 253.00, 228.00, 253.00, 228.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(70, 'Czarny Niedźwiedź', 55, 286, 245.00, 270.00, 245.00, 270.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(71, 'Krótkowłosy Niedźwieżuk', 60, 312, 284.00, 311.00, 284.00, 311.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(72, 'Ogromny Pająk', 65, 312, 338.00, 338.00, 338.00, 338.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(73, 'Spaczony Satyr', 70, 336, 387.00, 387.00, 387.00, 387.00, 'Ardulith', '', '', '', 'earth;strong', 'earth'),
(74, 'Czarny Worg', 75, 360, 425.00, 459.00, 459.00, 425.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(75, 'Złowrogi Allip', 80, 448, 440.00, 440.00, 440.00, 440.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(76, 'Leśny Centaur', 85, 476, 498.00, 498.00, 464.00, 464.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(77, 'Czarnogrzywy Lew', 90, 504, 502.00, 538.00, 538.00, 502.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(78, 'Złoty Jednorożec', 95, 532, 560.00, 560.00, 560.00, 560.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(79, 'Złudna Bestia', 100, 560, 600.00, 600.00, 600.00, 600.00, 'Ardulith', '', '', '', 'wind;weak', 'wind'),
(80, 'Srebny Pegaz', 105, 588, 662.00, 620.00, 662.00, 620.00, 'Ardulith', '', '', '', 'wind;strong', 'wind'),
(81, 'Dwugłowa Aranea', 110, 616, 680.00, 680.00, 680.00, 680.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(82, 'Pajęczonogi Ettercap', 115, 644, 720.00, 720.00, 720.00, 720.00, 'Ardulith', '', '', '', 'water;medium', 'water'),
(83, 'Czworopalczasta Meduza', 120, 672, 784.00, 736.00, 784.00, 736.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(84, 'Bengalski Tygrys', 125, 700, 776.00, 826.00, 826.00, 776.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(85, 'Leśna Wiedźma', 130, 832, 840.00, 840.00, 840.00, 840.00, 'Ardulith', '', '', '', 'fire;weak', 'fire'),
(86, 'Białogrzywy Girallon', 135, 918, 854.00, 908.00, 854.00, 908.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(87, 'Skrzydlaty Koszmar', 140, 896, 920.00, 920.00, 920.00, 920.00, 'Ardulith', '', '', '', 'wind;medium', 'wind'),
(88, 'Wściekły Wilkołak', 145, 928, 990.00, 932.00, 990.00, 932.00, 'Ardulith', '', '', '', 'fire;weak', 'fire'),
(89, 'Jaskiniowy Niedźwiedź', 150, 960, 1000.00, 1000.00, 1000.00, 1000.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(90, 'Bagienny Troll', 155, 1054, 1010.00, 1072.00, 1010.00, 1072.00, 'Ardulith', '', '', '', 'earth;medium', 'earth'),
(91, 'Brunatna Mantikora', 160, 1024, 1112.00, 1048.00, 1112.00, 1048.00, 'Ardulith', '', '', '', 'wind;strong', 'wind'),
(92, 'Wynaturzony Yuan-ti', 165, 1056, 1120.00, 1120.00, 1120.00, 1120.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(93, 'Ognisty Wywern', 170, 1088, 1194.00, 1126.00, 1194.00, 1126.00, 'Ardulith', '', '', '', 'fire;strong', 'fire'),
(94, 'Ziemny Żywiołak', 175, 1190, 1166.00, 1236.00, 1166.00, 1236.00, 'Ardulith', '', '', '', 'earth;strong', 'earth'),
(95, 'Złotoskóry Chuul', 180, 1296, 1240.00, 1240.00, 1240.00, 1240.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(96, 'Mroczny Mastiff', 185, 1332, 1318.00, 1244.00, 1318.00, 1244.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(97, 'Zielony Slaad', 190, 1368, 1340.00, 1340.00, 1340.00, 1340.00, 'Ardulith', '', '', '', 'earth;weak', 'earth'),
(98, 'Olbrzymi Drzewiec', 195, 1404, 1362.00, 1440.00, 1362.00, 1440.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(99, 'Czarny Lammasu', 200, 1440, 1420.00, 1500.00, 1500.00, 1420.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(100, 'Sukkub', 205, 1476, 1562.00, 1480.00, 1562.00, 1480.00, 'Ardulith', '', '', '', 'fire;medium', 'fire'),
(101, 'Szary Rozpruwacz', 210, 1596, 1538.00, 1622.00, 1538.00, 1622.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(102, 'Tygrysi Beschalor', 215, 1548, 1684.00, 1684.00, 1598.00, 1598.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(103, 'Czerwonooki Couatl', 220, 1584, 1700.00, 1700.00, 1700.00, 1700.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(104, 'Czworonożna Hydra', 225, 1620, 1760.00, 1760.00, 1760.00, 1760.00, 'Ardulith', '', '', '', 'water;strong', 'water'),
(105, 'Zielony Smok', 230, 1840, 1840.00, 1840.00, 1840.00, 1840.00, 'Ardulith', '', '', '', 'none;none', 'none'),
(106, 'Szpadyzor', 69, 332, 380.00, 375.00, 380.00, 375.00, 'Altara', 'Pazur Szpadyzora;Łapa Szpadyzora;Oko Szpadyzora;Czaszka Szpadyzora', '55;77;95;100', 'Szpadyzor wyglądem przypomina zwykłego czarnego kota, aczkolwiek jest od niego większy i bardziej niebezpieczny. Jak wcześniej było wspomniane jest koloru czarnego, ma ostre długie pazury, a jego oczy świecą się na zielono. Stwór ten zamieszkuje najciemniejsze zakamarki lasów. Atakuje z ukrycia i jedynie co jego ofiara zobaczy przed śmiercią to błysk jego świecących na zielono oczu, które wręcz paraliżują ofiarę.', 'none;none', 'none'),
(107, 'Kaussaula', 28, 150, 87.00, 84.00, 87.00, 84.00, 'Altara', '', '55;77;95;100', '', 'fire;medium', 'water'),
(108, 'Humkur', 72, 386, 357.00, 385.00, 472.00, 357.00, 'Altara', 'Noga Humkura;Skrzydła Humkura;Głowa Humkura;Dziób Humkura', '55;77;95;100', '', 'wind;weak', 'none'),
(109, 'Masterczułka', 69, 332, 419.00, 413.00, 419.00, 337.00, 'Altara', 'Czułki Masterczułki;Głowa Masterczułki;Odwłok Masterczułki;Bijcie Masterczułki', '55;77;95;100', '', 'wind;weak', 'wind'),
(110, 'Numur', 99, 560, 649.00, 590.00, 607.00, 607.00, 'Altara', 'Czaszka Numura;Kostka Numura;Żołądek Numura;Oko Numura', '55;77;95;100', '', 'water;medium', 'water');
CREATE TABLE IF NOT EXISTS `bonuses` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(60) NOT NULL,
  `desc` text NOT NULL,
  `cost` int(11) NOT NULL,
  `levels` tinyint(1) NOT NULL,
  `trigger` varchar(255) NOT NULL,
  `bonus` tinyint(2) NOT NULL,
  `race` varchar(255) NOT NULL,
  `clas` varchar(255) NOT NULL,
  KEY `id` (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=52 ;
INSERT INTO `bonuses` (`id`, `name`, `desc`, `cost`, `levels`, `trigger`, `bonus`, `race`, `clas`) VALUES
(1, 'Mistrz górnictwa', 'Premia w wysokości +2% do umiejętności Górnictwo podczas wydobywania minerałów', 3, 5, 'mining', 2, 'All;', 'Rzemieślnik;'),
(2, 'Kryształowy górnik', 'Premia +5% do umiejętności Górnictwo podczas wydobywania kryształów.', 5, 5, 'crystal', 5, 'Krasnolud;Gnom;', 'Rzemieślnik;'),
(3, 'Mistrz zielarstwa', 'Premia w wysokości +2% do Zielarstwa podczas zbierania ziół.', 3, 5, 'herbalism', 2, 'All;', 'Rzemieślnik;'),
(4, 'Zielarz zdrowia', 'Premia w wysokości +5% do Zielarstwa podczas zbierania Illani.', 5, 5, 'illani', 5, 'Elf,Gnom;', 'Rzemieślnik;'),
(5, 'Adamantytowy górnik', 'Premia +5% do umiejętności Górnictwo podczas wydobywania adamantium.', 5, 5, 'adamantium', 5, 'Krasnolud;Gnom;', 'Rzemieślnik;'),
(6, 'Miedziany górnik', 'Premia +5% do umiejętności Górnictwo podczas wydobywania rudy miedzi.', 5, 5, 'copper', 5, 'Krasnolud;Gnom;', 'Rzemieślnik;'),
(7, 'Cynkowy górnik', 'Premia +5% do umiejętności Górnictwo podczas wydobywania rudy cynku.', 5, 5, 'zinc', 5, 'Krasnolud;Gnom;', 'Rzemieślnik;'),
(8, 'Cynowy górnik', 'Premia +5% do umiejętności Górnictwo podczas wydobywania rudy cyny.', 5, 5, 'tin', 5, 'Krasnolud;Gnom;', 'Rzemieślnik;'),
(9, 'Żelazny górnik', 'Premia +5% do umiejętności Górnictwo podczas wydobywania rudy żelaza.', 5, 5, 'iron', 5, 'Krasnolud;Gnom;', 'Rzemieślnik;'),
(10, 'Węglowy górnik', 'Premia +5% do umiejętności Górnictwo podczas wydobywania węgla.', 5, 5, 'coal', 5, 'Krasnolud;Gnom;', 'Rzemieślnik;'),
(11, 'Zielarz odtrutek', 'Premia w wysokości +5% do Zielarstwa podczas zbierania Illanias.', 5, 5, 'illanias', 5, 'Elf,Gnom;', 'Rzemieślnik;'),
(12, 'Zielarz magii', 'Premia w wysokości +5% do Zielarstwa podczas zbierania Nutari.', 5, 5, 'nutari', 5, 'Elf,Gnom;', 'Rzemieślnik;'),
(13, 'Zielarz trucizn', 'Premia w wysokości +5% do Zielarstwa podczas zbierania Dynallca.', 5, 5, 'dynallca', 5, 'Elf,Gnom;', 'Rzemieślnik;'),
(14, 'Mistrz kowalstwa', 'Premia w wysokości +2% do umiejętności Kowalstwo podczas wykonywania przedmiotów.', 3, 5, 'smith', 2, 'All;', 'Rzemieślnik;'),
(15, 'Mistrz stolarstwa', 'Premia w wysokości +2% do umiejętności Stolarstwo podczas wykonywania przedmiotów.', 3, 5, 'carpentry', 2, 'All;', 'Rzemieślnik;'),
(16, 'Zbrojmistrz', 'Premia w wysokości +5% do umiejętności Kowalstwo podczas wykonywania broni.', 5, 5, 'weaponsmith', 5, 'Gnom;Krasnolud;', 'Rzemieślnik;'),
(17, 'Płatnerz zbroi', 'Premia w wysokości +5% do umiejętności Kowalstwo podczas wykonywania zbrój.', 5, 5, 'armorsmith', 5, 'Gnom;Krasnolud;', 'Rzemieślnik;'),
(18, 'Płatnerz hełmów', 'Premia w wysokości +5% do umiejętności Kowalstwo podczas wykonywania hełmów.', 5, 5, 'helmsmith', 5, 'Gnom;Krasnolud;', 'Rzemieślnik;'),
(19, 'Płatnerz nagolenników', 'Premia w wysokości +5% do umiejętności Kowalstwo podczas wykonywania nagolenników.', 5, 5, 'legsmith', 5, 'Gnom;Krasnolud;', 'Rzemieślnik;'),
(20, 'Płatnerz tarcz', 'Premia w wysokości +5% do umiejętności Kowalstwo podczas wykonywania tarcz.', 5, 5, 'shieldsmith', 5, 'Gnom;Krasnolud;', 'Rzemieślnik;'),
(21, 'Kowal', 'Premia w wysokości +5% do umiejętności Kowalstwo podczas wykonywania narzędzi.', 5, 5, 'armorsmith', 5, 'All;', 'Rzemieślnik;'),
(52, 'Łuczarz', 'Premia w wysokości +5% do umiejętności Stolarstwo podczas wykonywania łuków.', 5, 5, 'bowyer', 5, 'Hobbit;Gnom;', 'Rzemieślnik;'),
(22, 'Wytwórca strzał', 'Premia w wysokości +5% do umiejętności Stolarstwo podczas wykonywania strzał.', 5, 5, 'arrowmaker', 5, 'Hobbit;Gnom;', 'Rzemieślnik;'),
(23, 'Mistrz jubilerstwa', 'Premia w wysokości +2% do umiejętności Jubilerstwo podczas wykonywania pierścieni.', 3, 5, 'jewellry', 2, 'All;', 'Rzemieślnik;'),
(24, 'Mistrz drwalnictwa', 'Premia w wysokości +2% do umiejętności Drwalnictwo podczas wyrębu drewna.', 3, 5, 'lumberjack', 2, 'All;', 'Rzemieślnik;'),
(25, 'Mistrz hutnictwa', 'Premia w wysokości +2% do umiejętności Hutnictwo podczas wytapiania sztabek oraz przetapiania przedmiotów.', 3, 5, 'smelting', 2, 'All;', 'Rzemieślnik;'),
(26, 'Mistrz hodowli', 'Premia w wysokości +2% do umiejętności Hodowla podczas rozmnażania chowańców.', 3, 5, 'breeding', 2, 'All;', 'Rzemieślnik;'),
(27, 'Mag bojowy', 'Premia w wysokości +2% do siły czarów bojowych.', 3, 5, 'bspells', 2, 'All;', 'Mag;'),
(28, 'Ochronna magia', 'Premia w wysokości +2% do siły czarów obronnych.', 3, 5, 'dspells', 2, 'All;', 'Mag;'),
(29, 'Mag ognia', 'Premia +5% do siły czarów bojowych i obronnych z żywiołu ognia.', 5, 5, 'fire', 5, 'All;', 'Mag;'),
(30, 'Mag wody', 'Premia +5% do siły czarów bojowych i obronnych z żywiołu wody.', 5, 5, 'water', 5, 'All;', 'Mag;'),
(31, 'Mag powietrza', 'Premia +5% do siły czarów bojowych i obronnych z żywiołu powietrza.', 5, 5, 'wind', 5, 'All;', 'Mag;'),
(32, 'Mag ziemi', 'Premia +5% do siły czarów bojowych i obronnych z żywiołu ziemi.', 5, 5, 'earth', 5, 'All;', 'Mag;'),
(33, 'Umagiczniacz', 'Premia +5% do umiejętności Rzucanie czarów podczas umagiczniania przedmiotów.', 5, 5, 'enchant', 5, 'All;', 'Mag;'),
(34, 'Sokole oko', 'Premia +5% do trafienia bronią dystansową podczas walki.', 5, 5, 'eagleeye', 5, 'Elf;Hobbit;Człowiek;', 'Wojownik;'),
(35, 'Taktyka', 'Premia +5% do szybkości podczas walki z przeciwnikami.', 5, 5, 'tactic', 5, 'All;', 'Wojownik;'),
(36, 'Szał bitewny', 'Premia +5% do obrażeń i kara -5% do obrony podczas walk z przeciwnikami.', 5, 5, 'rage', 5, 'All;', 'Barbarzyńca;'),
(37, 'Silna Wola', 'Premia +5% do siły woli podczas walki z przeciwnikami.', 5, 5, 'will', 5, 'All;', 'Wojownik;'),
(38, 'Niewiara w magię', 'Premia +5% do siły woli podczas walk z przeciwnikami.', 5, 5, 'antimagic', 5, 'All;', 'Barbarzyńca;'),
(39, 'Mistrz broni', 'Premia +2% do umiejętności walki (bronią białą bądź strzelania).', 3, 5, 'weaponmaster', 2, 'All;', 'Wojownik;Barbarzyńca;'),
(40, 'Obrońca', 'Premia +5% do obrony podczas walk z przeciwnikami.', 5, 5, 'defender', 5, 'Człowiek;Krasnolud;', 'Wojownik;'),
(41, 'Zwinne palce', 'Premia +2% do umiejętności Złodziejstwo podczas okradania innych graczy.', 3, 5, 'pickpocket', 2, 'All;', 'Złodziej;'),
(42, 'Włamywacz', 'Premia +5% do umiejętności złodziejstwo podczas okradania banku oraz sklepów.', 5, 5, 'steal', 5, 'All;', 'Złodziej;'),
(43, 'Szpieg', 'Premia +2% do szpiegowania i sabotowania klanów', 3, 5, 'spy', 2, 'All;', 'Złodziej;'),
(44, 'Zabójca', 'Premia +1% do trafienia krytycznego podczas walki.', 3, 5, 'assasin', 1, 'All;', 'Złodziej;'),
(45, 'Czujność', 'Premia +2 % do umiejętności Spostrzegawczość.', 3, 5, 'seeker', 2, 'All;', 'All;'),
(46, 'Szybkostopy', 'Premia +2% do cechy Szybkość.', 5, 5, 'speed', 2, 'Hobbit;Elf;Człowiek;', 'All;'),
(47, 'Żelazne dłonie', 'Premia +2% do cechy Siła.', 5, 5, 'strength', 2, 'Krasnolud;Jaszczuroczłek;Człowiek;', 'All;'),
(48, 'Żelazna wola', 'Premia +2% do cechy Siła Woli.', 5, 5, 'wisdom', 2, 'All;', 'All;'),
(49, 'Analityk', 'Premia +2% do cechy Inteligencja.', 5, 5, 'inteli', 2, 'All;', 'All;'),
(50, 'Zwinne ciało', 'Premia +2% do cechy Zręczność.', 5, 5, 'agility', 2, 'Hobbit;Elf;Gnom;', 'All;'),
(51, 'Żelazne zdrowie', 'Premia +2% do cechy Wytrzymałość.', 5, 5, 'condition', 2, 'Hobbit;Krasnolud;Jaszczuroczłek;Człowiek;', 'All;'),
(53, 'Mistrz alchemii', 'Premia w wysokości +2% do umiejętności Alchemia podczas wykonywania mikstur', 3, 5, 'alchemy', 2, 'All;', 'Rzemieślnik;'),
(54, 'Alchemik magii', 'Premia w wysokości +5% do Alchemi podczas wykonywania mikstur z Nutari.', 5, 5, 'amana', 5, 'Gnom;', 'Rzemieślnik;'),
(55, 'Alchemik życia', 'Premia w wysokości +5% do Alchemi podczas wykonywania mikstur z Nutari.', 5, 5, 'ahealth', 5, 'Gnom;', 'Rzemieślnik;'),
(56, 'Alchemik trucizn', 'Premia w wysokości +5% do Alchemi podczas wykonywania trucizn.', 5, 5, 'apoison', 5, 'Gnom;', 'Rzemieślnik;'),
(57, 'Alchemik odtrutek', 'Premia w wysokości +5% do Alchemi podczas wykonywania odtrutek.', 5, 5, 'aantidote', 5, 'Gnom;', 'Rzemieślnik;');
ALTER TABLE `tribes` ADD `traps` TINYINT( 3 ) NOT NULL DEFAULT '0',
ADD `agents` TINYINT( 3 ) NOT NULL DEFAULT '0',
ADD `dagents` TINYINT( 3 ) NOT NULL DEFAULT '0';
ALTER TABLE `aktywacja` DROP `lang`;
ALTER TABLE `aktywacja` ADD `gtype` VARCHAR( 1 ) NOT NULL;
CREATE TABLE IF NOT EXISTS `teams` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `leader` int(11) NOT NULL,
  `slot1` int(11) NOT NULL,
  `slot2` int(11) NOT NULL DEFAULT '0',
  `slot3` int(11) NOT NULL DEFAULT '0',
  `slot4` int(11) NOT NULL DEFAULT '0',
  `slot5` int(11) NOT NULL DEFAULT '0',
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
CREATE TABLE `bug_comments` (
`id` int( 11 ) NOT NULL AUTO_INCREMENT ,
`bugid` int( 11 ) NOT NULL DEFAULT '0',
`author` varchar( 40 ) NOT NULL DEFAULT '',
`body` text NOT NULL ,
`time` date DEFAULT NULL ,
KEY `id` ( `id` )
) ENGINE = MYISAM DEFAULT CHARSET = utf8;
ALTER TABLE `vallars` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST ,
ADD INDEX ( `id` );
CREATE TABLE IF NOT EXISTS `attacks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `attacker` int(11) NOT NULL,
  `attacked` int(11) NOT NULL,
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
