ALTER TABLE `players` CHANGE `energy` `energy` DOUBLE( 11, 2 ) NOT NULL DEFAULT '100.00',
CHANGE `max_energy` `max_energy` DOUBLE( 11, 2 ) NOT NULL DEFAULT '100.00',
CHANGE `hp` `hp` INT( 11 ) UNSIGNED NOT NULL DEFAULT '10',
CHANGE `max_hp` `max_hp` INT( 11 ) NOT NULL DEFAULT '10';
ALTER TABLE `players`
  DROP `level`,
  DROP `exp`,
  DROP `strength`,
  DROP `agility`,
  DROP `inteli`,
  DROP `szyb`,
  DROP `wytrz`,
  DROP `wisdom`,
  DROP `ability`,
  DROP `atak`,
  DROP `unik`,
  DROP `magia`,
  DROP `alchemia`,
  DROP `shoot`,
  DROP `fletcher`,
  DROP `leadership`,
  DROP `breeding`,
  DROP `mining`,
  DROP `lumberjack`,
  DROP `herbalist`,
  DROP `jeweller`,
  DROP `thievery`,
  DROP `perception`,
  DROP `metallurgy`;
ALTER TABLE `players` ADD `stats` VARCHAR( 2048 ) NOT NULL DEFAULT 'strength:Siła,0,0,0;agility:Zręczność,0,0,0;condition:Kondycja,0,0,0;speed:Szybkość,0,0,0;inteli:Inteligencja,0,0,0;wisdom:Siła Woli,0,0,0;';
ALTER TABLE `players` ADD `skills` VARCHAR( 4096 ) NOT NULL DEFAULT 'smith:Kowalstwo,0,0;shoot:Strzelectwo,0,0;alchemy:Alchemia,0,0;dodge:Uniki,0,0;carpentry:Stolarstwo,0,0;magic:Rzucanie Czarów,0,0;attack:Walka Bronią,0,0;leadership:Dowodzenie,0,0;breeding:Hodowla,0,0;mining:Górnictwo,0,0;lumberjack:Drwalnictwo,0,0;herbalism:Zielarstwo,0,0;jewellry:Jubilerstwo,0,0;smelting:Hutnictwo,0,0;thievery:Złodziejstwo,0,0;perception:Spostrzegawczość,0,0;';
