[package]
name = "vallheru-web"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
vallheru-domain = { path = "../domain" }
vallheru-data = { path = "../data" }

axum.workspace = true
hex.workspace = true
include_dir.workspace = true
lettre.workspace = true
mime_guess.workspace = true
minijinja.workspace = true
rand.workspace = true
serde.workspace = true
sqlx.workspace = true
toml.workspace = true
tower.workspace = true
tokio.workspace = true
tracing.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
tower = { workspace = true, features = ["util"] }
serde_json.workspace = true
sqlx.workspace = true
