[package]
name = "vallheru-domain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
argon2.workspace = true
md-5.workspace = true
hex.workspace = true
rand.workspace = true
tracing.workspace = true
