[package]
name = "vallheru-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
default-run = "vallheru"

[lints]
workspace = true

[[bin]]
name = "vallheru"
path = "src/main.rs"

[dependencies]
vallheru-web = { path = "../web" }
vallheru-domain = { path = "../domain" }
vallheru-data = { path = "../data" }

axum.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http.workspace = true
serde.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true
thiserror.workspace = true
anyhow.workspace = true
